package org.bravestudy.minto.warmup.sample.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 게시판_견적 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardEstimate implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판 상품견적 ID. */
	private Long boardProductEstimateId;

	/** 게시판 게시글. */
	private BoardArticle boardArticle;

	/** 이름. */
	private String name;

	/** 핸드폰. */
	private String mobile;

	/** 이메일. */
	private String email;

	/** 견적 분류. */
	private Object estimateType;

	/** 문의내용. */
	private String contents;

	/** 견적등록일 . */
	private Date estimateDate;

	/** 게시판_견적 상품리스트 목록. */
	private Set<BoardEstimateProduct> boardEstimateProductSet;

	/**
	 * 생성자.
	 */
	public BoardEstimate() {
		this.boardEstimateProductSet = new HashSet<BoardEstimateProduct>();
	}

	/**
	 * 게시판 상품견적 ID을 설정합니다..
	 * 
	 * @param boardProductEstimateId
	 *            게시판 상품견적 ID
	 */
	public void setBoardProductEstimateId(Long boardProductEstimateId) {
		this.boardProductEstimateId = boardProductEstimateId;
	}

	/**
	 * 게시판 상품견적 ID을 가져옵니다..
	 * 
	 * @return 게시판 상품견적 ID
	 */
	public Long getBoardProductEstimateId() {
		return this.boardProductEstimateId;
	}

	/**
	 * 게시판 게시글을 설정합니다..
	 * 
	 * @param boardArticle
	 *            게시판 게시글
	 */
	public void setBoardArticle(BoardArticle boardArticle) {
		this.boardArticle = boardArticle;
	}

	/**
	 * 게시판 게시글을 가져옵니다..
	 * 
	 * @return 게시판 게시글
	 */
	public BoardArticle getBoardArticle() {
		return this.boardArticle;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param name
	 *            이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 핸드폰을 설정합니다..
	 * 
	 * @param mobile
	 *            핸드폰
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * 핸드폰을 가져옵니다..
	 * 
	 * @return 핸드폰
	 */
	public String getMobile() {
		return this.mobile;
	}

	/**
	 * 이메일을 설정합니다..
	 * 
	 * @param email
	 *            이메일
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * 이메일을 가져옵니다..
	 * 
	 * @return 이메일
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 견적 분류을 설정합니다..
	 * 
	 * @param estimateType
	 *            견적 분류
	 */
	public void setEstimateType(Object estimateType) {
		this.estimateType = estimateType;
	}

	/**
	 * 견적 분류을 가져옵니다..
	 * 
	 * @return 견적 분류
	 */
	public Object getEstimateType() {
		return this.estimateType;
	}

	/**
	 * 문의내용을 설정합니다..
	 * 
	 * @param contents
	 *            문의내용
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * 문의내용을 가져옵니다..
	 * 
	 * @return 문의내용
	 */
	public String getContents() {
		return this.contents;
	}

	/**
	 * 견적등록일 을 설정합니다..
	 * 
	 * @param estimateDate
	 *            견적등록일 
	 */
	public void setEstimateDate(Date estimateDate) {
		this.estimateDate = estimateDate;
	}

	/**
	 * 견적등록일 을 가져옵니다..
	 * 
	 * @return 견적등록일 
	 */
	public Date getEstimateDate() {
		return this.estimateDate;
	}

	/**
	 * 게시판_견적 상품리스트 목록을 설정합니다..
	 * 
	 * @param boardEstimateProductSet
	 *            게시판_견적 상품리스트 목록
	 */
	public void setBoardEstimateProductSet(Set<BoardEstimateProduct> boardEstimateProductSet) {
		this.boardEstimateProductSet = boardEstimateProductSet;
	}

	/**
	 * 게시판_견적 상품리스트를 추가합니다..
	 * 
	 * @param boardEstimateProduct
	 *            게시판_견적 상품리스트
	 */
	public void addBoardEstimateProduct(BoardEstimateProduct boardEstimateProduct) {
		this.boardEstimateProductSet.add(boardEstimateProduct);
	}

	/**
	 * 게시판_견적 상품리스트 목록을 가져옵니다..
	 * 
	 * @return 게시판_견적 상품리스트 목록
	 */
	public Set<BoardEstimateProduct> getBoardEstimateProductSet() {
		return this.boardEstimateProductSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardProductEstimateId == null) ? 0 : boardProductEstimateId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardEstimate other = (BoardEstimate) obj;
		if (boardProductEstimateId == null) {
			if (other.boardProductEstimateId != null) {
				return false;
			}
		} else if (!boardProductEstimateId.equals(other.boardProductEstimateId)) {
			return false;
		}
		return true;
	}

}
