package org.bravestudy.minto.warmup.sample.vo;

import java.io.Serializable;

/**
 * 게시판_고객센터 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardCustomer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판_고객선터ID. */
	private Long boardCustomerId;

	/** 게시판 게시글. */
	private BoardArticle boardArticle;

	/** 주문ID. */
	private Long orderId;

	/**
	 * 생성자.
	 */
	public BoardCustomer() {
	}

	/**
	 * 게시판_고객선터ID을 설정합니다..
	 * 
	 * @param boardCustomerId
	 *            게시판_고객선터ID
	 */
	public void setBoardCustomerId(Long boardCustomerId) {
		this.boardCustomerId = boardCustomerId;
	}

	/**
	 * 게시판_고객선터ID을 가져옵니다..
	 * 
	 * @return 게시판_고객선터ID
	 */
	public Long getBoardCustomerId() {
		return this.boardCustomerId;
	}

	/**
	 * 게시판 게시글을 설정합니다..
	 * 
	 * @param boardArticle
	 *            게시판 게시글
	 */
	public void setBoardArticle(BoardArticle boardArticle) {
		this.boardArticle = boardArticle;
	}

	/**
	 * 게시판 게시글을 가져옵니다..
	 * 
	 * @return 게시판 게시글
	 */
	public BoardArticle getBoardArticle() {
		return this.boardArticle;
	}

	/**
	 * 주문ID을 설정합니다..
	 * 
	 * @param orderId
	 *            주문ID
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * 주문ID을 가져옵니다..
	 * 
	 * @return 주문ID
	 */
	public Long getOrderId() {
		return this.orderId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardCustomerId == null) ? 0 : boardCustomerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardCustomer other = (BoardCustomer) obj;
		if (boardCustomerId == null) {
			if (other.boardCustomerId != null) {
				return false;
			}
		} else if (!boardCustomerId.equals(other.boardCustomerId)) {
			return false;
		}
		return true;
	}

}
