package org.bravestudy.minto.warmup.sample.vo;

import java.io.Serializable;

/**
 * 게시판_상품문의 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardProductQuestion implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판 상품문의 ID. */
	private Long boardProductQuestionId;

	/** 게시판 게시글. */
	private BoardArticle boardArticle;

	/** 상품 ID. */
	private Long productId;

	/** 평점. */
	private Short grade;

	/**
	 * 생성자.
	 */
	public BoardProductQuestion() {
	}

	/**
	 * 게시판 상품문의 ID을 설정합니다..
	 * 
	 * @param boardProductQuestionId
	 *            게시판 상품문의 ID
	 */
	public void setBoardProductQuestionId(Long boardProductQuestionId) {
		this.boardProductQuestionId = boardProductQuestionId;
	}

	/**
	 * 게시판 상품문의 ID을 가져옵니다..
	 * 
	 * @return 게시판 상품문의 ID
	 */
	public Long getBoardProductQuestionId() {
		return this.boardProductQuestionId;
	}

	/**
	 * 게시판 게시글을 설정합니다..
	 * 
	 * @param boardArticle
	 *            게시판 게시글
	 */
	public void setBoardArticle(BoardArticle boardArticle) {
		this.boardArticle = boardArticle;
	}

	/**
	 * 게시판 게시글을 가져옵니다..
	 * 
	 * @return 게시판 게시글
	 */
	public BoardArticle getBoardArticle() {
		return this.boardArticle;
	}

	/**
	 * 상품 ID을 설정합니다..
	 * 
	 * @param productId
	 *            상품 ID
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * 상품 ID을 가져옵니다..
	 * 
	 * @return 상품 ID
	 */
	public Long getProductId() {
		return this.productId;
	}

	/**
	 * 평점을 설정합니다..
	 * 
	 * @param grade
	 *            평점
	 */
	public void setGrade(Short grade) {
		this.grade = grade;
	}

	/**
	 * 평점을 가져옵니다..
	 * 
	 * @return 평점
	 */
	public Short getGrade() {
		return this.grade;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardProductQuestionId == null) ? 0 : boardProductQuestionId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardProductQuestion other = (BoardProductQuestion) obj;
		if (boardProductQuestionId == null) {
			if (other.boardProductQuestionId != null) {
				return false;
			}
		} else if (!boardProductQuestionId.equals(other.boardProductQuestionId)) {
			return false;
		}
		return true;
	}

}
