package org.bravestudy.minto.warmup.sample.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 게시판_게시글_파일 업로드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardArticleFileupload implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판 게시글 파일업로드 ID. */
	private Long boardArticleFileuploadId;

	/** 게시판 게시글. */
	private BoardArticle boardArticle;

	/** 파일 URL. */
	private String fileUrl;

	/** 실제 파일명. */
	private String fileRealname;

	/** 파일 사이즈 . */
	private Integer fileSize;

	/** 등록일 . */
	private Date createDate;

	/**
	 * 생성자.
	 */
	public BoardArticleFileupload() {
	}

	/**
	 * 게시판 게시글 파일업로드 ID을 설정합니다..
	 * 
	 * @param boardArticleFileuploadId
	 *            게시판 게시글 파일업로드 ID
	 */
	public void setBoardArticleFileuploadId(Long boardArticleFileuploadId) {
		this.boardArticleFileuploadId = boardArticleFileuploadId;
	}

	/**
	 * 게시판 게시글 파일업로드 ID을 가져옵니다..
	 * 
	 * @return 게시판 게시글 파일업로드 ID
	 */
	public Long getBoardArticleFileuploadId() {
		return this.boardArticleFileuploadId;
	}

	/**
	 * 게시판 게시글을 설정합니다..
	 * 
	 * @param boardArticle
	 *            게시판 게시글
	 */
	public void setBoardArticle(BoardArticle boardArticle) {
		this.boardArticle = boardArticle;
	}

	/**
	 * 게시판 게시글을 가져옵니다..
	 * 
	 * @return 게시판 게시글
	 */
	public BoardArticle getBoardArticle() {
		return this.boardArticle;
	}

	/**
	 * 파일 URL을 설정합니다..
	 * 
	 * @param fileUrl
	 *            파일 URL
	 */
	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	/**
	 * 파일 URL을 가져옵니다..
	 * 
	 * @return 파일 URL
	 */
	public String getFileUrl() {
		return this.fileUrl;
	}

	/**
	 * 실제 파일명을 설정합니다..
	 * 
	 * @param fileRealname
	 *            실제 파일명
	 */
	public void setFileRealname(String fileRealname) {
		this.fileRealname = fileRealname;
	}

	/**
	 * 실제 파일명을 가져옵니다..
	 * 
	 * @return 실제 파일명
	 */
	public String getFileRealname() {
		return this.fileRealname;
	}

	/**
	 * 파일 사이즈 을 설정합니다..
	 * 
	 * @param fileSize
	 *            파일 사이즈 
	 */
	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	/**
	 * 파일 사이즈 을 가져옵니다..
	 * 
	 * @return 파일 사이즈 
	 */
	public Integer getFileSize() {
		return this.fileSize;
	}

	/**
	 * 등록일 을 설정합니다..
	 * 
	 * @param createDate
	 *            등록일 
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * 등록일 을 가져옵니다..
	 * 
	 * @return 등록일 
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardArticleFileuploadId == null) ? 0 : boardArticleFileuploadId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardArticleFileupload other = (BoardArticleFileupload) obj;
		if (boardArticleFileuploadId == null) {
			if (other.boardArticleFileuploadId != null) {
				return false;
			}
		} else if (!boardArticleFileuploadId.equals(other.boardArticleFileuploadId)) {
			return false;
		}
		return true;
	}

}
