package org.bravestudy.minto.warmup.sample.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 게시판 게시글 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardArticleAppend implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판 게시글 댓글 ID . */
	private Long boardArticleAppendId;

	/** 게시판 게시글. */
	private BoardArticle boardArticle;

	/** 댓글 내용. */
	private String contents;

	/** 등록일 . */
	private Date registDate;

	/**
	 * 생성자.
	 */
	public BoardArticleAppend() {
	}

	/**
	 * 게시판 게시글 댓글 ID 을 설정합니다..
	 * 
	 * @param boardArticleAppendId
	 *            게시판 게시글 댓글 ID 
	 */
	public void setBoardArticleAppendId(Long boardArticleAppendId) {
		this.boardArticleAppendId = boardArticleAppendId;
	}

	/**
	 * 게시판 게시글 댓글 ID 을 가져옵니다..
	 * 
	 * @return 게시판 게시글 댓글 ID 
	 */
	public Long getBoardArticleAppendId() {
		return this.boardArticleAppendId;
	}

	/**
	 * 게시판 게시글을 설정합니다..
	 * 
	 * @param boardArticle
	 *            게시판 게시글
	 */
	public void setBoardArticle(BoardArticle boardArticle) {
		this.boardArticle = boardArticle;
	}

	/**
	 * 게시판 게시글을 가져옵니다..
	 * 
	 * @return 게시판 게시글
	 */
	public BoardArticle getBoardArticle() {
		return this.boardArticle;
	}

	/**
	 * 댓글 내용을 설정합니다..
	 * 
	 * @param contents
	 *            댓글 내용
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * 댓글 내용을 가져옵니다..
	 * 
	 * @return 댓글 내용
	 */
	public String getContents() {
		return this.contents;
	}

	/**
	 * 등록일 을 설정합니다..
	 * 
	 * @param registDate
	 *            등록일 
	 */
	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	/**
	 * 등록일 을 가져옵니다..
	 * 
	 * @return 등록일 
	 */
	public Date getRegistDate() {
		return this.registDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardArticleAppendId == null) ? 0 : boardArticleAppendId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardArticleAppend other = (BoardArticleAppend) obj;
		if (boardArticleAppendId == null) {
			if (other.boardArticleAppendId != null) {
				return false;
			}
		} else if (!boardArticleAppendId.equals(other.boardArticleAppendId)) {
			return false;
		}
		return true;
	}

}
