package org.bravestudy.minto.warmup.sample.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 상담내용 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CounselContent implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 상담접수게시판. */
	private BoardCounsel boardCounsel;

	/** 상담내용. */
	private String contents;

	/** 상담자. */
	private Long counselPerson;

	/** 생성자. */
	private String createId;

	/** 생성일. */
	private Date createDate;

	/** 수정자. */
	private String modifyId;

	/** 수정일. */
	private Date modifyDate;

	/**
	 * 생성자.
	 */
	public CounselContent() {
	}

	/**
	 * 상담접수게시판을 설정합니다..
	 * 
	 * @param boardCounsel
	 *            상담접수게시판
	 */
	public void setBoardCounsel(BoardCounsel boardCounsel) {
		this.boardCounsel = boardCounsel;
	}

	/**
	 * 상담접수게시판을 가져옵니다..
	 * 
	 * @return 상담접수게시판
	 */
	public BoardCounsel getBoardCounsel() {
		return this.boardCounsel;
	}

	/**
	 * 상담내용을 설정합니다..
	 * 
	 * @param contents
	 *            상담내용
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * 상담내용을 가져옵니다..
	 * 
	 * @return 상담내용
	 */
	public String getContents() {
		return this.contents;
	}

	/**
	 * 상담자을 설정합니다..
	 * 
	 * @param counselPerson
	 *            상담자
	 */
	public void setCounselPerson(Long counselPerson) {
		this.counselPerson = counselPerson;
	}

	/**
	 * 상담자을 가져옵니다..
	 * 
	 * @return 상담자
	 */
	public Long getCounselPerson() {
		return this.counselPerson;
	}

	/**
	 * 생성자을 설정합니다..
	 * 
	 * @param createId
	 *            생성자
	 */
	public void setCreateId(String createId) {
		this.createId = createId;
	}

	/**
	 * 생성자을 가져옵니다..
	 * 
	 * @return 생성자
	 */
	public String getCreateId() {
		return this.createId;
	}

	/**
	 * 생성일을 설정합니다..
	 * 
	 * @param createDate
	 *            생성일
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * 생성일을 가져옵니다..
	 * 
	 * @return 생성일
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * 수정자을 설정합니다..
	 * 
	 * @param modifyId
	 *            수정자
	 */
	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	/**
	 * 수정자을 가져옵니다..
	 * 
	 * @return 수정자
	 */
	public String getModifyId() {
		return this.modifyId;
	}

	/**
	 * 수정일을 설정합니다..
	 * 
	 * @param modifyDate
	 *            수정일
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * 수정일을 가져옵니다..
	 * 
	 * @return 수정일
	 */
	public Date getModifyDate() {
		return this.modifyDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardCounsel == null) ? 0 : boardCounsel.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CounselContent other = (CounselContent) obj;
		if (boardCounsel == null) {
			if (other.boardCounsel != null) {
				return false;
			}
		} else if (!boardCounsel.equals(other.boardCounsel)) {
			return false;
		}
		return true;
	}

}
